apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: skiapp-ingress-nginx
  namespace: team-riker
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: #skiapp.{{ .Values.spec.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: skiapp-service
              servicePort: 80
