apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skiapp-ingress-nginx
  namespace: team-riker
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: #skiapp.{{ .Values.spec.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skiap-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: TargetGroupBinding
metadata:
  name: nginx-ingress-tgb
  namespace: ingress-nginx
spec:
  service: ingress-nginx-controller
  targetGroups:
    - arn:aws:elasticloadbalancing:us-west-2:124043462474:targetgroup/eks-blueprint-tg-blue/37996df7d43aa97a
